name: Release Docs Zip File

on:
  release:
    types: [ published ]

env:
  IMAGE_NAME_BASE: ${{ github.repository_owner }}

jobs:
  add_docs_zip_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive deployment-relevant documentation.
        run: |
          ARCHIVE_FILE_NAME="authority-portal-release-${GITHUB_REF#refs/tags/v}-deployment-docs.zip"
          echo "ARCHIVE_FILE_NAME=$ARCHIVE_FILE_NAME" >> $GITHUB_ENV
          zip -r -q $ARCHIVE_FILE_NAME \
            README.md \
            CHANGELOG.md \
            docs/deployment-guide/goals/production/* \
            docs/deployment-guide/goals/sirius/remote/Caddyfile \
            docs/deployment-guide/goals/sirius/remote/docker-compose.yaml \
            docs/product/* \
            authority-portal-keycloak/mds-theme/* \
            authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.json
      - name: Upload deployment-relevant documentation
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE_FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
