name: Trivy Security Scan

on:
  push:
  workflow_dispatch:

jobs:
  security_scan:
    name: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run static analysis (rootfs)
        uses: aquasecurity/trivy-action@0.26.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db #mirror because of https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db #mirror because of https://github.com/aquasecurity/trivy-action/issues/389
        with:
          scan-type: "rootfs"
          scanners: "vuln,misconfig"
          ignore-unfixed: true
          format: 'table'
          severity: "CRITICAL,HIGH"
      - name: Run static analysis (repo)
        uses: aquasecurity/trivy-action@0.26.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db #mirror because of https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db #mirror because of https://github.com/aquasecurity/trivy-action/issues/389
        with:
          scan-type: "repo"
          scanners: "vuln,misconfig"
          ignore-unfixed: true
          format: 'table'
          severity: "CRITICAL,HIGH"
