name: Trivy Security Scan

on:
  push:
  workflow_dispatch:

jobs:
  security_scan:
    name: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run static analysis (rootfs)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "rootfs"
          scanners: "vuln,misconfig"
          ignore-unfixed: true
          format: 'table'
          severity: "CRITICAL,HIGH"
      - name: Run static analysis (repo)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "repo"
          scanners: "vuln,misconfig"
          ignore-unfixed: true
          format: 'table'
          severity: "CRITICAL,HIGH"
